### ISSUE TITLE
CI does not run tests in CedarJavaFFI

### ISSUE THREAD

**Issue by cdisselkoen** [cedar-policy/cedar-java#126]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar-java/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar-java/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

`CedarJavaFFI` has its own tests, but the CI in this repo does not run them; as a result, they are broken on `main` as of this writing.  We should either modify the CI to run these tests, or remove the tests if we don't think they add value and prefer to have only the tests in `CedarJava`.

### Expected behavior

`main` does not contain broken tests.

### Reproduction steps

1. Checkout main
2. `cd CedarJavaFFI`
3. `cargo test`

**Comment by cdisselkoen** [comment]
Somewhat related and probably could be addressed at the same time: CedarJava and/or CedarJavaFFI could use more tests for error paths, ensuring that various failure cases are properly reported across the FFI boundary (both sides agree on the structure of JSON for these error cases).

**Comment by khieta** [comment]
Closed by #128?

**Comment by cdisselkoen** [comment]
Yes
