### ISSUE TITLE
Add support for the new schema syntax

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar-java#130]
### Category

User level API changes

### Describe the feature you'd like to request

Add support for new schema syntax introduced in Cedar v3.1. This is required to support the new integration tests in https://github.com/cedar-policy/cedar-integration-tests.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
The new schema syntax is supported in the FFI as of cedar-policy/cedar#793, so this should only need work here in this repo.
