### ISSUE TITLE
Support conversion to Json for Policies

### ISSUE THREAD

**Issue by mark-creamer-amazon** [cedar-policy/cedar-java#171]
### Category

User level API changes

### Describe the feature you'd like to request

We need to provide a method to convert human readable policy syntax to the json representation. When we build our Java Policy object, we don't currently have a method to retrieve the JSON string corresponding to the tied `policySrc`.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Heads up that we'll be adding this functionality to the Cedar Json FFI once we get to [cedar#854](https://github.com/cedar-policy/cedar/issues/854) (likely next week). 

It's also possible to implemented this functionality directly in `interface.rs`, but probably better to reuse the Json FFI where possible.
