### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by mustafaakin** [cedar-policy/cedar-java#18]
### Category

Other

### Describe the feature you'd like to request

Can you release this project to Maven central so that we can just use it without additional local building involved?

### Describe the solution you'd like

I want to just use the library as a dependency.

### Describe alternatives you've considered

Building from scratch. Which won't work for everyone.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
This is something we're interested in. The main reason we haven't done it is that it's easier to build the Rust code than to  distribute shared library files. I'll look into this at some point but there are some other things I'm working on currently so it won't be immediately.

**Comment by andrewmwells-amazon** [comment]
Correct me if I'm wrong, but with your proposal the library users will still need to build the Rust code on their machine, correct?

What if we built and published the shared library files with Github actions (basically our current CI + https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle for each platform we're going to support)?

**Comment by mustafaakin** [comment]
Yes, that approach is better. Looking forward to it. Are you going to publish to maven central or Github packages?

**Comment by andrewmwells-amazon** [comment]
I'll publish to the Maven central repo hosted by Sonatype.

**Comment by andrewmwells-amazon** [comment]
Closed with #49
