### ISSUE TITLE
bug: facing error in CedarJava build

### ISSUE THREAD

**Issue by duttarnab** [cedar-policy/cedar-java#184]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar-java/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar-java/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Other

### Describe the bug

Getting below error after executing `./gradlew build` for CedarJava project.

```
 = note: error: symbol .rust_psm_on_stack_end not attached to any (sub)section
              note: while parsing /Users/arnabdutta/Projects/cedar/java/cedar-java/CedarJavaFFI/target/aarch64-apple-darwin/release/deps/libpsm-d479c8604f5ef459.rlib(e4479bd7784abb10-aarch_aapcs64.o)
          

error: could not compile `cedar-policy` (lib) due to 1 previous error

> Task :compileFFI FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/arnabdutta/Projects/cedar/java/cedar-java/CedarJava/build.gradle' line: 136

* What went wrong:
Execution failed for task ':compileFFI'.
> Process 'command 'cargo'' finished with non-zero exit value 101

```

### Expected behavior

The build should be successful.

### Reproduction steps

1. git clone -b release/3.2.x https://github.com/cedar-policy/cedar-java.git
2. cd cedar-java/CedarJavaFFI && cargo build
3. cd ../CedarJava && ./gradlew build

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

```
 = note: error: symbol .rust_psm_on_stack_end not attached to any (sub)section
              note: while parsing /Users/arnabdutta/Projects/cedar/java/cedar-java/CedarJavaFFI/target/aarch64-apple-darwin/release/deps/libpsm-d479c8604f5ef459.rlib(e4479bd7784abb10-aarch_aapcs64.o)
          

error: could not compile `cedar-policy` (lib) due to 1 previous error

> Task :compileFFI FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/arnabdutta/Projects/cedar/java/cedar-java/CedarJava/build.gradle' line: 136

* What went wrong:
Execution failed for task ':compileFFI'.
> Process 'command 'cargo'' finished with non-zero exit value 101

```

**Comment by mark-creamer-amazon** [comment]
I believe I had seen this before, could you please first confirm that you're using [Zig](https://ziglang.org/learn/getting-started/) 0.11.0 and JDK 17 or later?

From the [prerequisites](https://github.com/cedar-policy/cedar-java/tree/main/CedarJava#prerequisites).

**Comment by shaobo-he-aws** [comment]
Closed this issue for now. Please feel free to reopen it if you haven further information.
