### ISSUE TITLE
`NoDecision` is currently unused

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar-java#37]
### Category

User level API changes

### Describe the feature you'd like to request

The documentation of `AuthorizationResponse` says "`Decision` will be set to `NoDecision` in the event of a parse error in submitted slice." But this doesn't actually seem to be the case. Afaict, `NoDecision` is never used. The current behavior of `isAuthorized` is to return `Deny` in the case of a parse error. If #34 is merged, then the behavior will become to thrown a `BadRequestException` instead of returning a valid reponse.

### Describe the solution you'd like

We should either remove the `NoDecision` field, or change the behavior of `isAuthorized` to use it.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Seems to me that the `BadRequestException` is better than `NoDecision`, but I'm not familiar with conventions for idiomatic Java
