### ISSUE TITLE
Support parsing multiple policies

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar-java#38]
### Category

User level API changes

### Describe the feature you'd like to request

It would be useful to provide an API that takes as input a string (or file) consisting of multiple policies and returns a `Set<policy>`. We currently only provide a constructor for a single `Policy`, which encourages hacky tricks like splitting an input policy file on semicolons (which will break when comments, strings, or eids contain this character).

### Describe the solution you'd like

Ideally the API should just reuse what's available in Rust rather than building a new parser.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by bman654** [comment]
As far as I can tell, there isn't currently a way to just load an entire cedar policy file that has multiple policies, correct?  I need to instantiate `Policy` objects one by one (like using your hacky trick above)?

**Comment by khieta** [comment]
Yes, I believe this is still the case. Pull requests welcome! Most of our development effort is spent on the [Rust implementation](https://github.com/cedar-policy/cedar) (which has all the nice APIs you'd expect).

**Comment by bman654** [comment]
I was thinking about this more last night b/c I was also concerned with the cost of API calls in this wrapper - the serialization/deserialization of your policy set (slice) on each auth request.  Seems like it could get prohibitive for a large policy set.  Was thinking about how it would be nice if the Java objects were just proxies or handles to Rust objects.

Then realized that probably what I'm looking for is a Java binding to the [cedar-local-agent](https://github.com/cedar-policy/cedar-local-agent).  I don't know what the use case is for `cedar-java` but the use case I was looking for was to be able to load a Policy Set from somewhere and make authorization requests from Java, all in the same process.  Seems like the API surface of `cedar-local-agent` is closer to what I am looking for, it just doesn't have a Java wrapper.

If I ever get some free time I'll work on that.

**Comment by mark-creamer-amazon** [comment]
Merged [165](https://github.com/cedar-policy/cedar-java/pull/165) and closing. Please reopen if anything else is needed
