### ISSUE TITLE
Support the new EntityUID format for integration tests

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar-java#51]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

`cedar-java` should update to support the new format for integration tests

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by khieta** [comment]
Closing since this issue is stale. Integration tests are currently working for Java code.
