### ISSUE TITLE
CedarJava should support partial evaluation

### ISSUE THREAD

**Issue by ygrignon-sfdc** [cedar-policy/cedar-java#74]
### Category

User level API changes

### Describe the feature you'd like to request

Now that FFI expose partial evaluation, CedarJava should support it.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
Resolved by #75
