### ISSUE TITLE
Decide on mechanism for annotating experimental APIs

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar-java#77]
### Category

User level API changes

### Describe the feature you'd like to request

Before releasing the  APIs in #75 we need to decide how to distinguish experimental APIs from stable.

We should at least document stability in java-doc comments. This is easy add, but easy for users to miss.

A more robust mechanism might take advantage of Java annotations  Annotations support automated processing in ways that could allow us to reflect the annotation into the javadocs or write a tool that warns when using an experimental API. Some options are: 

* [Use @Deprecated](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Deprecated.html). This feels like an abuse of the annotation, but according to [JEP 277: Enhanced Deprecation](https://openjdk.org/jeps/277) (which seems pretty official), "deprecating" experimental APIs is one of the intended use cases for the annotation. Advantages to this are that there's no additional libraries/code we need to use it, and library consumers get a warning from the compiler when using it without need to apply any other checks. Deprecation annotation show up in JavaDocs, and we can use the separate `@deprecated` javadoc tag to explain that it's
* [Use `@Beta`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/annotations/Beta.html) from Guava. This feels more semantically correct, but ISTM that `@Beta` isn't intended for use outside of Guava. We already depend on Guava, so this doesn't add any new dependencies. Library consumers would need to [add an extra tool](https://github.com/google/guava-beta-checker) to their build if they want to verify that they don't depend on beta APIs.
* Define a custom annotation. We could make this `@Experimental` to be consistent with the Rust library. Custom annotations will show up in the docs if we add `@Documented` to the annotation definition. Unless we write it ourselves, there wouldn't be any tool to automatically check that the annotation isn't used. Writing that tool would be easy. See https://stackoverflow.com/a/1754823

We could also consider excluding these features from the mean release. They could then be released in a separate version, e.g., 3.0.1 would exclude these features while 3.0.1-experimental would have all experimental features

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by ygrignon-sfdc** [comment]
@john-h-kastner-aws I added an Experimental annotation to my partial evaluation PR. I'm happy to revert it if we don't want to mix concerns or add this issue reference to my PR if you think that's the right way forward.

**Comment by john-h-kastner-aws** [comment]
Resolved to `@Experimental` options by #75
