### ISSUE TITLE
Add code format checks to Java CI

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar-java#93]
### Category

Internal refactors/changes

### Describe the feature you'd like to request

We should add some sort of Java code format check to our CI workflow. We enforce formatting with `cargo fmt` across all our Rust code, but have nothing for Java.

Two options I'm aware of: 

* [clang-format](https://clang.llvm.org/docs/ClangFormat.html). This does actually support Java code formatting. Very configurable, which in some ways is not a feature for a formatting tool.
* [Google Java Format](https://github.com/google/google-java-format). This has some long standing open issue for [poor lambda formatting](https://github.com/google/google-java-format/issues/19), and [lack of and `format: off` directive](https://github.com/google/google-java-format/issues/137).

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Resolved by #158
